services:
  playwright-runner:
    container_name: Playwright
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    volumes:
    #remove nodemodules from volume
      - .:/app
      - pw_node_modules:/app/node_modules
      - pw_node_modules:/app/.pnpm-store
      - pw_node_modules:/root
    working_dir: /app
    command: 
      - sh
      - -c
      - |
        npm install pnpm -g
        pnpm install
        pnpm exec playwright install
        pnpm exec playwright test --port 3000 --host 0.0.0.0
#        pnpm exec playwright show-report --port 3000 --host 0.0.0.0
    environment:
      - PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000
    ports:
      - "4321:4321"
      - "5173:5173"
      - "9323:9323"
      - "3000:3000"
volumes:
  pw_node_modules: