/**
 * CSP policy directives (non-hash parts).
 * script-src hashes are injected automatically by scripts/generateCspHashes.ts at build time.
 */
export const cspPolicy = {
  'default-src': [
    "'self'",
  ],
  'script-src': {
    static: [
      "'self'",
    ],
    // Hashes for scripts produced by Vercel's build environment that differ from local builds.
    // Add new ones here when violations appear for hashes not generated by the local build.
    buildEnvHashes: [
      "'sha256-BrDhGE1lwa85arfXcrBxSo+n37uVSX5CAROXnIM6Q+g='",
      "'sha256-kq+o1kpk7kk0Qt8m8OePmXS/+PA6WWL4ICxEtJomMro='",
    ],
    externalDomains: [
      'https://www.googletagmanager.com',
      'https://cdn.jsdelivr.net',
      'https://challenges.cloudflare.com',
      'https://static.cloudflareinsights.com',
    ],
    // hashes injected at build time
  },
  'style-src': [
    "'self'",
    "'unsafe-inline'",
  ],
  'img-src': [
    "'self'",
    'data:',
    'blob:',
    'https://www.giorgiosaud.io',
    'https://platform.linkedin.com',
    'https://cc.sj-cdn.net',
    'https://developers.google.com',
    'https://avatars.githubusercontent.com',
  ],
  'connect-src': [
    "'self'",
    'https://www.google-analytics.com',
    'https://analytics.google.com',
    'https://www.googletagmanager.com',
    'https://cdn.jsdelivr.net',
  ],
  'worker-src': [
    "'self'",
    'blob:',
  ],
  'frame-src': [
    'https://challenges.cloudflare.com',
  ],
  'object-src': [
    "'none'",
  ],
  'base-uri': [
    "'self'",
  ],
  'form-action': [
    "'self'",
  ],
} as const
